pipeline:
  name: qw1
  identifier: qw1
  projectIdentifier: Testing
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.helix_github_harness
        build: <+input>
  stages:
    - stage:
        name: helix_stage
        identifier: helix_stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: kubernetes
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.helix_github_harness
                    cloneDirectory: helix
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.helix_narayan_repo
                    repo: narayansharma12/helix
                    tags:
                      - latest
                    caching: true
    - stage:
        name: helix_deploy
        identifier: helix_deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: kubernetes_service
          environment:
            environmentRef: iat
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: new_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
